name: Build SAMD11

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches: [ test, master ]
  pull_request:
    branches: [ test, master ]
    types: [closed]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Build SAMD11 App Firmware
        run: |
          make -C platform/samd11/make -f Makefile_bl_5k clean all
          cd tools/uf2_transform && ./uf2conv.sh

      - name: Upload SAMD11 APP Firmware
        uses: actions/upload-artifact@v4
        with:
          name: xiao-samd11-app-firmware
          path: tools/uf2_transform/xiao_samd11.uf2

      - name: Build SAMD11 Bootloader Firmware
        run: |
          cd ~ && git clone https://github.com/Seeed-Studio/uf2-samdx1.git
          cd uf2-samdx1 && git checkout samd11
          make BOARD=XIAO_samd11 -j4
          cd ~ && ls
