name: Build SAMD11

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'
  push:
    branches: [ test, master ]
  pull_request:
    branches: [ test, master ]
    types: [closed]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi

      - name: Build
        run: make -C platform/samd11/make -f Makefile_bl_5k clean all
